import styles from "./Layout.module.scss"
import logoPiramide from "../static/logo-piramide.svg"
import logoOceanica from "../static/oceanica_original.png"
import Image from 'next/image'
import LogoutIcon from '@mui/icons-material/Logout';
import { useRouter } from 'next/router';
import { useSwitch } from "@/Components/Context/contextSwitch";
export const metadata = {
  title: 'Prueba ',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  const router = useRouter();
  const { company, setCompany } = useSwitch()

  const handleTokenLayour = () => {
    sessionStorage.clear()
    router.push('/')
  }


  return (
    <main lang="en">
      <div className={styles.container_layout}>
        <div className={styles.app_bar}>
          <div className={styles.div1}>
            <Image
              src={company ? logoOceanica : logoPiramide}
              alt={company ? "Oceanica de Seguros" : "Piramide Seguros"}

              style={{
                maxHeight: "3rem",
                maxWidth: "10rem",
                textAlign: "center"
              }}
            />
          </div>
          {router.route !== "/" ?<div className={styles.div2}><LogoutIcon style={{ cursor: "pointer" }} onClick={handleTokenLayour} /></div>:null}
        </div>

        {children}
      </div>
    </main>
  )
}
